/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      colors: {
        "surface-bright": "#faf8ff",
        "surface-container": "#eaedff",
        "inverse-primary": "#c0c1ff",
        "on-secondary-container": "#fffbff",
        "surface-variant": "#dae2fd",
        "secondary": "#6b38d4",
        "error": "#ba1a1a",
        "tertiary": "#00628d",
        "on-secondary": "#ffffff",
        "secondary-container": "#8455ef",
        "on-surface": "#131b2e",
        "background": "#faf8ff",
        "on-background": "#131b2e",
        "on-tertiary-fixed-variant": "#004c6e",
        "surface-container-high": "#e2e7ff",
        "surface-container-low": "#f2f3ff",
        "tertiary-fixed-dim": "#89ceff",
        "on-secondary-fixed-variant": "#5516be",
        "on-primary-fixed": "#07006c",
        "on-error": "#ffffff",
        "outline-variant": "#c7c4d7",
        "tertiary-container": "#007cb1",
        "surface-tint": "#494bd6",
        "primary-container": "#6063ee",
        "on-tertiary-fixed": "#001e2f",
        "surface": "#faf8ff",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary-container": "#fffbff",
        "tertiary-fixed": "#c9e6ff",
        "surface-container-highest": "#dae2fd",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#d0bcff",
        "on-tertiary-container": "#fcfcff",
        "surface-dim": "#d2d9f4",
        "inverse-surface": "#283044",
        "on-surface-variant": "#464554",
        "inverse-on-surface": "#eef0ff",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "secondary-fixed": "#e9ddff",
        "primary": "#4648d4",
        "outline": "#767586",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "primary-fixed": "#e1e0ff",
        "on-secondary-fixed": "#23005c",
        google: {
          dark: '#0f0f11',
          surface: '#1c1c1f',
          border: '#2d2d33',
          purple: '#bbaaff',
          glow: 'rgba(187, 170, 255, 0.15)'
        }
      }
    }
  },
  plugins: [],
}
