version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8085:80"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - cloud_library:/app/cloud_library
      - temp_downloads:/app/temp_downloads
    restart: always

volumes:
  cloud_library:
  temp_downloads:
