import React from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';

export default function TermsOfService() {
  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="min-h-screen pt-24 pb-32 px-4 md:px-8 max-w-4xl mx-auto text-on-surface"
    >
      <Link to="/" className="inline-flex items-center gap-2 text-primary hover:underline mb-8 font-label-lg" aria-label="Go back to Home">
        <span className="material-symbols-outlined" aria-hidden="true">arrow_back</span>
        Back to Home
      </Link>
      
      <h1 className="font-display-md md:font-display-lg text-primary mb-2 font-bold">Terms and Conditions</h1>
      <p className="font-body-lg text-on-surface-variant mb-8">Last Updated: {new Date().toLocaleDateString()}</p>
      
      <div className="space-y-8 font-body-md leading-relaxed text-on-surface-variant">
        <section>
          <h2 className="font-title-lg text-on-surface font-bold mb-3">1. Acceptance of Terms</h2>
          <p>
            By accessing or using Curator AI, you agree to be bound by these Terms and Conditions. If you disagree with any part of the terms, you may not access the service.
          </p>
        </section>

        <section>
          <h2 className="font-title-lg text-on-surface font-bold mb-3">2. Service Description and AI Claims</h2>
          <p>
            Curator AI is a tool that helps aggregate, process, and curate educational or entertainment content using third-party Artificial Intelligence models (such as Gemini and Groq). 
          </p>
          <p className="mt-2 text-error font-semibold">
            <strong>Disclaimer regarding AI outputs:</strong> We make no unsupported claims about the absolute accuracy of the AI-generated curriculum or roadmaps. The AI outputs are generated by external providers and should be independently verified. We do not guarantee "flawless" or "world's best" educational structures; the service operates as an automated organizational assistant.
          </p>
        </section>

        <section>
          <h2 className="font-title-lg text-on-surface font-bold mb-3">3. Copyright and Intellectual Property</h2>
          <p>
            Curator AI functions as an intermediary tool processing public URLs (e.g., from YouTube) for personal offline use. 
          </p>
          <ul className="list-disc pl-5 space-y-2 mt-2">
            <li>We do not host, own, or distribute copyrighted video or audio content on our servers.</li>
            <li>Users are strictly responsible for ensuring their personal, local downloading complies with the Terms of Service of the originating platform (e.g., YouTube) and their local copyright laws.</li>
            <li>All UI images, logos, and non-user-generated assets are properly licensed or utilize open-source generators (like Dicebear) with full commercial use rights.</li>
          </ul>
        </section>

        <section>
          <h2 className="font-title-lg text-on-surface font-bold mb-3">4. Reviews and Testimonials</h2>
          <p>
            Curator AI strictly prohibits the use of fake reviews or misleading testimonials in our promotional materials. Any testimonials displayed on our site are provided by real users of the platform and reflect their authentic experiences.
          </p>
        </section>

        <section>
          <h2 className="font-title-lg text-on-surface font-bold mb-3">5. Bring Your Own Key (BYOK) Responsibility</h2>
          <p>
            You are responsible for the usage, billing, and security of your personal API keys (Google Gemini, Groq, etc.) inputted into the application. Curator AI is not liable for any API charges incurred on your personal accounts while using the application.
          </p>
        </section>

        <section>
          <h2 className="font-title-lg text-on-surface font-bold mb-3">6. Governing Law</h2>
          <p>
            These Terms shall be governed and construed in accordance with the laws of California, United States, without regard to its conflict of law provisions.
          </p>
        </section>

        <section>
          <h2 className="font-title-lg text-on-surface font-bold mb-3">7. Contact Information</h2>
          <address className="not-italic bg-surface-container p-4 rounded-xl border border-outline-variant/30">
            <strong>Curator AI Legal Dept</strong><br/>
            Email: <a href="mailto:legal@curatorai.invalid" className="text-primary hover:underline">legal@curatorai.invalid</a><br/>
            Business Entity: Curator Technologies LLC<br/>
            Address: 123 Tech Boulevard, Suite 400, San Francisco, CA 94105
          </address>
        </section>
      </div>
    </motion.div>
  );
}
